### ISSUE TITLE
Support tree data

### ISSUE THREAD

**Issue by cultureulterior** [spectresystems/spectre.console#144]
Hi- 

This looks really good.  Does it support tree data, e.g like this?
```
  ┬ Tree:
  ├─┬ test-5-f6d0fda5
  │ └─  system5
  ├─┬ test-8-f039bf15
  │ ├─  system8
  ┴ └─  system9
```

**Comment by patriksvensson** [comment]
@cultureulterior That is something that I've planned to implement once some other things are in place. Thanks for the suggestion! 👍

**Comment by mcon** [comment]
Can probably close this now :+1:
