### ISSUE TITLE
Resizing the console makes the images disappear

### ISSUE THREAD

**Issue by rold2007** [spectresystems/spectre.console#149]
I just tested the new canvas. It works well, except that when the console is resized the console turns black!

![2020-11-25 (6)](https://user-images.githubusercontent.com/507551/100228850-aa951a00-2f66-11eb-8e86-59f58ea44f00.png)

After maximizing:
![2020-11-25 (7)](https://user-images.githubusercontent.com/507551/100228857-abc64700-2f66-11eb-8900-a2f768b8b58d.png)

**Comment by patriksvensson** [comment]
@rold2007 This has nothing to do with Spectre.Console, but is related to the terminal in question preserves output during resizing.

**Comment by patriksvensson** [comment]
@rold2007 Verified that this is confined to Windows Terminal, so I'm closing this issue for now. I Will see if there's a way to work around it, but not sure what that would be.

**Comment by rold2007** [comment]
@patriksvensson Thanks for your answer. I understand your point, but at the same time I was surprised to see that the text (image titles) was still there but the image "pixels" weren't. I don't see why the text would be there but not the pixels if everything is drawn as "text".

**Comment by patriksvensson** [comment]
@rold2007 I see your point, but this seems to be a bug in Windows Terminal and not really sure what I can do about that 😕

If you have any suggestions, they are welcome.

**Comment by rold2007** [comment]
@patriksvensson I looked into it a little bit but I haven't finished yet. As you can see from the first screenshot, if I print 'a' instead of spaces it "works". The only drawback is that for some reason the color gets spread out to the right of the "image".

![2020-11-26 (2)](https://user-images.githubusercontent.com/507551/100351512-e398c180-302e-11eb-9bf3-fd30e3a918af.png)

I started testing with different kind of [unicode spaces](http://jkorpela.fi/chars/spaces.html) and U+00A0 gives a nicer result than printing a's, but the color still spreads. I will try to other kind of spaces, but let me know if you have an idea about the cause for the color spreading.

![2020-11-26 (3)](https://user-images.githubusercontent.com/507551/100351517-e4315800-302e-11eb-8325-19016081d5c3.png)

**Comment by rold2007** [comment]
To fix the color spread I tried adding a blank space before the LineBreak in the Canvas Render() method:
```
                yield return new Segment(new string('\u00A0', 1), new Style(background: Color.Default));
                yield return Segment.LineBreak;
```
It works better except for the third image which shows empty spaces when the console isn't wide enough...

Maximized console:
![2020-11-26 (4)](https://user-images.githubusercontent.com/507551/100353212-85b9a900-3031-11eb-8896-d91a1a59cc5d.png)

Default size console:
![2020-11-26 (5)](https://user-images.githubusercontent.com/507551/100353223-8baf8a00-3031-11eb-875e-95a448b0beb7.png)

@patriksvensson I'll see if I can come up with something better...
