### ISSUE TITLE
WriteException fails because of generic

### ISSUE THREAD

**Issue by zplan** [spectresystems/spectre.console#154]
When a stack trace contains a generic method the AnsiConsole.WriteException fails with the error message:
"Could not parse style T"

Example "text "string in Markup.cs :
_paragraph = MarkupParser.Parse(text, style);

[silver]Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.[/][yellow]SendAsync**[T]**[/][silver]([/][blue]HttpRequestMessage[/] [silver]message[/], [blue]Object[/] [silver]userState[/], [blue]CancellationToken[/] [silver]cancellationToken[/][silver])[/]

Expectation:
The used strings should be encoded so that special characters like [ and ] are not interfere with the color rendering.

**Comment by zplan** [comment]
@patriksvensson 
Thanks a lot for your fast reponse. I am using 0.30.0, 

Strange, I was not updating yet because the release notes mention only a typo fix and also the commit shows only a typo change:
"Fix typo in package description"
https://github.com/spectresystems/spectre.console/releases/tag/0.31.0

But after updating to 0.31.0 it seems to work. 
Sorry for that but how is this explainable?

**Comment by patriksvensson** [comment]
@zplan Great that it solved itself.

I don't update the release notes, so it just shows the commit the release was made from.
