### ISSUE TITLE
Support for Windows Terminal HyperLinks

### ISSUE THREAD

**Issue by bluemodus-acoats** [spectresystems/spectre.console#160]
I would be great to be able to use the Markdown like syntax to create clickable WIndows Hyperlinks.

https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-4-release/#hyperlink-support

**Comment by patriksvensson** [comment]
@bluemodus-acoats Thanks for the suggestion, but this is already supported. See `dotnet example links` for an example.

```csharp
if (AnsiConsole.Capabilities.SupportLinks)
{
    AnsiConsole.MarkupLine("[link=https://patriksvensson.se]Click to visit my blog[/]!");
}
else
{
    AnsiConsole.MarkupLine("[red]It looks like your terminal doesn't support links[/]");
    AnsiConsole.MarkupLine("[yellow](╯°□°)╯[/]︵ [blue]┻━┻[/]");
}
```
