### ISSUE TITLE
Setting the MaxValue of a ProgressTask increments the existing value

### ISSUE THREAD

**Issue by mgasparel** [spectresystems/spectre.console#163]
https://github.com/spectresystems/spectre.console/blob/acf01e056fbaeb19baa5cc1b66062579aa704576/src/Spectre.Console/Progress/ProgressTask.cs#L170

After assigning the MaxValue of a ProgressTask to a value of `20`, the ProgressTask.MaxValue becomes `120`

I'm currently working around this by subtracting 100 from the desired value.

**Comment by patriksvensson** [comment]
@mgasparel Thanks for reporting this! I've submitted a PR that fixes this (#164)

**Comment by patriksvensson** [comment]
This issue has been fixed and should be available in the preview version of Spectre.Console.
