### ISSUE TITLE
Add key(s) to easily cycle through prompt choices

### ISSUE THREAD

**Issue by billhenn** [spectresystems/spectre.console#166]
When I use the `Prompt` method and add several choices to it (e.g. `apple`, `banana`, `orange`), I'd love to be able to use something like up/down arrow keys to cycle through available choices rather than having to fully type each one out.  For instance in this scenario, the prompt would come up, I'd press down once and `apple` would be filled in.  If I pressed down arrow again, `banana` would replace it.  Then I press `Enter` and move on.

Another timesaver while I'm posting might be when you have choices, behave like PowerShell where you can type a letter (like `a`) and press `Tab` to have it auto-complete `apple`.

**Comment by patriksvensson** [comment]
@billhenn Excellent suggestions!

**Comment by stevenknox** [comment]
Similar to this would be checkboxes that can be navigated and selected using the keyboard. Ait would allow creation of a menu system similar to Yoman.

Im not sure if thats even possible with c# console apps, never came accross one on the wild

**Comment by patriksvensson** [comment]
@stevenknox Great suggestion! Would you mind creating a new issue for this?
