### ISSUE TITLE
Somehow allow exceptionless markup parsing

### ISSUE THREAD

**Issue by OlegGavrilov** [spectresystems/spectre.console#184]
**Is your feature request related to a problem? Please describe.**
When implemening ILogger, there is no way to have Spectre.Console not to throw when exceptions happens. 

**Describe the solution you'd like**
I would like to be able to implement custom MarkupParser which could swallow possible exceptions and render string as-is if there was any errors during rendering. Currently I can't do that because most of the classes and enums used are marked as internal.

**Describe alternatives you've considered**
I considered using throw-catch on the ILogger implementation level, but I would like to avoid that because of performance and reasons.

**Additional context**
The particular problem I'm having is that asp.net core likes to output stuff in square brackets, causong A LOT of "Could not find color or style" exceptions.

**Comment by patriksvensson** [comment]
@OlegGavrilov You can escape input by using the `string.EscapeMarkup()` extension method, or `Markup.Escape(string))` method.

```csharp
AnsiConsole.Markup("[red]{0}[/]", "Hello [World]".EscapeMarkup());
AnsiConsole.Markup("[red]{0}[/]", Markup.Escape("Hello [World]"));
```

More information at https://spectresystems.github.io/spectre.console/markup in the `Escaping format characters` section.

**Comment by iSeiryu** [comment]
I came here because I ran into the same issue.
This link returns 404 https://spectresystems.github.io/spectre.console/markup
This link works https://spectreconsole.net/markup

It'd be nice to enable search on that website.
