### ISSUE TITLE
Remaining arguments gets reparsed and split on spaces

### ISSUE THREAD

**Issue by MiloszKrajewski** [spectresystems/spectre.console#186]
Forked from spectresystems/spectre.cli#108 as requested

### Scenario

My application wraps around execution of other applications so I need to pass all arguments as is, for example, this:
```
app run cmd -- /c "set && pause"
```
tells my app (`app`) to run (`run`) other application (`cmd`) and pass "other arguments "as is" (`/c "set && pause"`).
I can see though that single argument "set && pause" get's reparsed as 3 "set", "&&", and "pause" (in `context.Remaining.Raw`) and I lose all clues that it ever was a single one.

### Code

```
class Program
{
	static void Main(string[] args)
	{
		var testArgs = new[] {
			"run",
			"cmd",
			"-e", "A=7",
			"-e", "B=10",
			"--",
			"/c", "set && pause"
		};
		var app = new CommandApp();
		app.Configure(config => config.AddCommand<RunCommand>("run"));
		app.Run(testArgs);
	}
}

public class RunCommand: Command<RunCommand.Settings>
{
	public class Settings: CommandSettings
	{
		[CommandArgument(0, "<EXECUTABLE>")]
		public string Executable { get; set; } = null!;

		[CommandOption("-e <VAR=VAL>")]
		public string[] Environment { get; set; } = Array.Empty<string>();
	}

	public override int Execute(CommandContext context, Settings settings)
	{
		Console.WriteLine(JsonConvert.SerializeObject(settings));
		Console.WriteLine(JsonConvert.SerializeObject(new {
			Parsed = context.Remaining.Parsed.ToArray(),
			Raw = context.Remaining.Raw.ToArray()
		}));
		return 0;
	}
}
```

### Expected

```
{"Executable":"cmd","Environment":["A=7","B=10"]}
{"Parsed":[],"Raw":["/c","set && pause"]}
```

### Actual

```
{"Executable":"cmd","Environment":["A=7","B=10"]}
{"Parsed":[],"Raw":["/c","set","&&","pause"]}
```

(See: `Raw` array, expected 2 arguments, received 4 arguments)

**Comment by patriksvensson** [comment]
@MiloszKrajewski Spectre.Cli have been merged into the `Spectre.Console` library. You might want to check the [Migration guide](https://spectresystems.github.io/spectre.console/cli/migration) to get this working.

### Problem

The way you define the input is never how an application would be receiving them.

```csharp
new[] {
    "run",
    "cmd",
    "-e", "A=7",
    "-e", "B=10",
    "--",
    "cmd", "/c", "set && pause"
};
```

It would expand to something like `run cmd -e A=7 -e B=10 -- cmd /c set && pause`.

### Solution

The parameters `run cmd -e A=7 -e B=10 -- cmd /c set && pause` should be sent to the application as 

```csharp
new[] {
    "run",
    "cmd",
    "-e", "A=7",
    "-e", "B=10",
    "--",
    "cmd", "/c", "\"set && pause\""
};
```

or from the command line `run cmd -e A=7 -e B=10 -- cmd /c "set && pause"`.

However, when I tried this I noticed a bug with string splitting. This has been corrected 
and should work as expected in `Spectre.Console` version `0.37`.

**Comment by MiloszKrajewski** [comment]
As long as it works (I didn't test it yet) it will be fine, but I'm afraid, you are not right saying: "The way you define the input is never how an application would be receiving them."

It does. 

I used this "sophisticated" application:

```
static void Main(string[] args)
{
    foreach (var a in args) Console.WriteLine($">>> {a} <<<");
}
```

and ran it with:

`app run cmd -e A=7 -e B=10 -- cmd /c "set && pause"`

and received:

```
>>> run <<<
>>> cmd <<<
>>> -e <<<
>>> A=7 <<<
>>> -e <<<
>>> B=10 <<<
>>> -- <<<
>>> cmd <<<
>>> /c <<<
>>> set && pause <<<
```

Please note: no quotes `set && pause` are stripped by PowerShell (but it seems by cmd.exe as well) and argument is passed without them.

![image](https://user-images.githubusercontent.com/4333436/103375591-7ddaa200-4ad2-11eb-92e8-5f6b815958af.png)

**Comment by patriksvensson** [comment]
@MiloszKrajewski Yes, different shells does different things. You will need to quote the arguments for it to work.

If you're going to specify the arguments yourself from a .NET program you will need to quote them explicitly.

**Comment by patriksvensson** [comment]
@MiloszKrajewski Try and see if the preview version works and get back to me. If there still are problems I can take another look tonight.

**Comment by MiloszKrajewski** [comment]
So I can work with that intercepting args and adding quotes around them.
Part of my confusion comes from the fact that they are treated differently before and after `--`, for example:

```
using System;
using System.Linq;
using Newtonsoft.Json;
using Spectre.Console.Cli;

namespace Spectre186
{
	class Program
	{
		static void Main(string[] args)
		{
			Console.WriteLine(JsonConvert.SerializeObject(args));
			new CommandApp<RunCommand>().Run(args);
		}
	}

	public class RunCommand: Command<RunCommand.Settings>
	{
		public class Settings: CommandSettings
		{
			[CommandArgument(0, "<ARGUMENT>")]
			public string[] Argument { get; set; } = null!;
		}

		public override int Execute(CommandContext context, Settings settings)
		{
			Console.WriteLine(JsonConvert.SerializeObject(settings.Argument));
			Console.WriteLine(JsonConvert.SerializeObject(context.Remaining.Raw.ToArray()));
			return 0;
		}
	}
}
```

This application prints:
1. arguments received (`string[] args`)
2. arguments parsed
3. arguments remaining (raw)

so when executed with:

`app XXX -- YYY`

I would expect:

1. received: `['XXX', '--', 'YYY']` (3 args)
2. parsed: `['XXX']` (1 arg)
3. remaining: `['YYY']` (1 arg)

...and that's what I get.

The confusion starts when parameters may have spaces in them:

```app "three words before" -- "three words after"```

as I get:

1. received: `["three words before","--","three words after"]` (3 args, as expected)
2. parsed: `["three words before"]` (1 arg, as expected)
3. remaining: `["three","words","after"]` (why three? I would expect one argument)

![image](https://user-images.githubusercontent.com/4333436/103378212-7b2f7b00-4ad9-11eb-8988-733f269fa7b7.png)

I would expected that from initial args all arguments after `--` are passed as-is (so one arg), because that's how it is on initial `string[] args`.

It is, of course, better than in previous version, as I can remove those extra args (behind '--') before passing them to `CommandApp.Run` and inject them into a command myself.

I know I'm a little chaotic, so if you have problem understanding my random stream of consciousness let me know.
Would like this project zipped?

**Comment by patriksvensson** [comment]
@MiloszKrajewski The first one is an argument, so the parser knows that the provided string is a string and treats the input as such. The remaining arguments however can't be reasoned about in the same fashion. When we tokenize it, we treat the raw parts as words if they're separated by space. `three words after` could theoretically be three consecutive commands `three`, `words`, and `after`.

We could perhaps change this but I would need to investigate it a bit tonight.

**Comment by MiloszKrajewski** [comment]
I guess I just interfered with some design choices you made and they are not fitting exactly how I would reason about "remaining arguments". I absolutely understand how difficult it could be to change something like this when API is settled and library is used (by others! who may actually rely on this behaviour).

What I can offer is the justification to not break those `"three words after"`:

They has been received as one `arg` (in `void Main(string[] args)` sense). 
If they have been received as one arg, therefore they must have been quoted on command line. 
If they have been quoted it must have happened intentionally (well, let's say I've quoting string in argument list by accident is low probability event).
If someone quoted them intentionally, he/she wanted them (words) to to be passed as one argument.

Anyway, regardless of your decision I know how to work around this, so I'm fine(-ish).

**Comment by patriksvensson** [comment]
@MiloszKrajewski I'm actually quite open to changing this behavior. Your justification makes sense 😊

**Comment by mhenggay21** [comment]
Hi Patrick Svensson,

Can i know details about joshua borre he prison in marikina city jail ?

Please answer my question.

Thank you ❤️

**Comment by patriksvensson** [comment]
@MiloszKrajewski I think I have a solution now for your problem.

@mhenggay21 I have no idea what you're talking about. Sorry.

**Comment by patriksvensson** [comment]
@MiloszKrajewski I've merged a potential fix to your problem. Could you check and see if it does what you expect it to now?

**Comment by MiloszKrajewski** [comment]
Yes it is what I would expect.
Although... I by accident discovered unrelated bug (I managed to freeze/infinite loop parser). 
I'll create new issue.

**Comment by patriksvensson** [comment]
@MiloszKrajewski Btw, I notice that you're trying to parse the form `-e FOO=BAR -e BAZ=QUX`. This is already supported. Just set the type of your `Environment` property to `ILookup<string, string>`, and it will be mapped automatically.

```csharp
public class Settings : CommandSettings
{
	[CommandArgument(0, "<ARGUMENT>")]
	public string[] Arguments { get; set; } = null!;

	[CommandOption("-e <VAR=VAL>")]
	public ILookup<string, string> Environment { get; set; }
}
```

The types `ILookup<string, string>`, `IDictionary<string, string>` and `IReadOnlyDictionary<string, string>` will work here, but the two latter will, of course, not support multiple values for the same key.
