### ISSUE TITLE
Parses freezes on ill-formed arguments

### ISSUE THREAD

**Issue by MiloszKrajewski** [spectresystems/spectre.console#198]
**Information**
 - OS: Window 10
 - Version: 0.36.0 + 0.36.1-preview0.5
 - Terminal: Cmder / Powershell

**Describe the bug**

Parser freezes when short option contains space (?) (I actually don't know exactly but it is easy to replice so it does not really matter what I know).

**To Reproduce**

Pass option and it's value quoted, for example instead of:

```app -o value```

do:

```app "-o value"```

**Expected behavior**

I assume it should be "unrecognized option" (because it is "-ovalue" with space in it).

**Screenshots**

![image](https://user-images.githubusercontent.com/4333436/103438935-6a454d80-4c30-11eb-9ea3-eada87758442.png)

**Additional context**

(find `<-- HERE` in code below)

```
using System;
using System.Linq;
using Newtonsoft.Json;
using Spectre.Console.Cli;

namespace Spectre186
{
	class Program
	{
		static void Main(string[] args)
		{
			// var testArgs = args;
			var testArgs = new[] {
				"run", 
				"-e", "A=7", 
				"-e B=3", // <-- HERE !!!
				"arg1",
				"arg2",
				"-e", "C=1",
			};
			var app = new CommandApp();
			app.Configure(config => config.AddCommand<RunCommand>("run"));
			app.Run(testArgs);
		}
	}

	public class RunCommand: Command<RunCommand.Settings>
	{
		public class Settings: CommandSettings
		{
			[CommandArgument(0, "<ARGUMENT>")]
			public string[] Arguments { get; set; } = null!;

			[CommandOption("-e <VAR=VAL>")]
			public string[] Environment { get; set; } = Array.Empty<string>();
		}

		public override int Execute(CommandContext context, Settings settings)
		{
			Console.WriteLine(JsonConvert.SerializeObject(settings));
			Console.WriteLine(
				JsonConvert.SerializeObject(
					new {
						Parsed = context.Remaining.Parsed.ToArray(),
						Raw = context.Remaining.Raw.ToArray()
					}));
			return 0;
		}
	}
}
```

PS.

Note: 

```app -ovalue```

fails as expected, but error message is a little bit confusing:

![image](https://user-images.githubusercontent.com/4333436/103439063-a4631f00-4c31-11eb-8dbe-df1eec7af5ea.png)

**Comment by patriksvensson** [comment]
I'll take a look at it later tonight. Great that you're finding edge cases like this!

**Comment by patriksvensson** [comment]
@MiloszKrajewski This should be fixed now. Could you take it to a spin and confirm?

**Comment by MiloszKrajewski** [comment]
It is working fine now (preview-0.9). Thanks!
