### ISSUE TITLE
Add Spectre.Console logo

### ISSUE THREAD

**Issue by khalidabuhakmeh** [spectresystems/spectre.console#20]
## Box Logo With Text

![box logo with text@2x](https://user-images.githubusercontent.com/228256/89416154-d6ac3700-d6fa-11ea-92a1-7546f8662808.png)

## Horizontal Logo With Black Text

![logo with black text@2x](https://user-images.githubusercontent.com/228256/89416156-d6ac3700-d6fa-11ea-860b-a8cf303f21be.png)

## Horizontal Logo with Gray Text

![logo with gray text@2x](https://user-images.githubusercontent.com/228256/89416159-d744cd80-d6fa-11ea-95f9-8cc3d24541ca.png)

## Plain Logo / Sticker

![logo@2x](https://user-images.githubusercontent.com/228256/89416160-d744cd80-d6fa-11ea-9f59-899b034a6b5f.png)

**Comment by patriksvensson** [comment]
That looks super nice! Do you have it as SVG or just in bitmap format?
