### ISSUE TITLE
Checkbox style menu with keyboard support

### ISSUE THREAD

**Issue by stevenknox** [spectresystems/spectre.console#210]
Checkboxes that can be navigated and selected using the keyboard. It would allow creation of a menu system similar to Yeoman (see gif below for an idea on keyboard support and bottom screenshot for checkbox style)

I'm not sure if that's even possible with C# console apps, never came across one on the wild

![ssotemplate](https://user-images.githubusercontent.com/1719323/103664700-74d25080-4f6a-11eb-8c55-8f90c71de7fd.gif)

![image](https://user-images.githubusercontent.com/1719323/103664899-af3bed80-4f6a-11eb-82a7-8984afa3e152.png)

**Comment by stevenknox** [comment]
Id be happy to put some leg work in on this but not sure where to even start in terms of how the menu/checkbox list would be created in a C# console app ?

**Comment by patriksvensson** [comment]
@stevenknox I'm going to take a look at this tonight.

**Comment by stevenknox** [comment]
Let me know if I can help in any way
