### ISSUE TITLE
Support for NO_COLOR (https://no-color.org)

### ISSUE THREAD

**Issue by KirillOsenkov** [spectresystems/spectre.console#211]
I just came across what I think is a nice informal standard:
https://no-color.org

Consider supporting it?

**Comment by patriksvensson** [comment]
@KirillOsenkov It should already be supported in the last preview version and will appear in 0.37.
Could you try with a preview version and see if it's working for you?

**Comment by KirillOsenkov** [comment]
If it doesn’t I’ll reopen. Thanks!
