### ISSUE TITLE
Question: CLI Settings Validation

### ISSUE THREAD

**Issue by turp** [spectresystems/spectre.console#213]
Love this project! 

Does the CLI framework contain a way to validate required settings properties before a command is executed? I have a number of commands with required and optional parameters, but it's not clear how to enforce that behavior. Any guidance would be appreciated.

**Comment by patriksvensson** [comment]
@turp Please re-open this under "Discussions" instead.

![image](https://user-images.githubusercontent.com/357872/104086306-0980cb00-5257-11eb-83c1-56b3de0d9612.png)

**Comment by patriksvensson** [comment]
Discussion: https://github.com/spectreconsole/spectre.console/discussions/217
