### ISSUE TITLE
Cannot run examples

### ISSUE THREAD

**Issue by lploumen** [spectresystems/spectre.console#215]
**Information**
 - OS: Windows, netcore 5.0
 - Terminal: Windows Terminal

**Describe the bug**
Cannot run the examples.
dotnet example is working fine and lists available examples but I can't run any.

![image](https://user-images.githubusercontent.com/11539944/104087519-95e3bb80-5260-11eb-8876-a4714ca60f12.png)

**Comment by patriksvensson** [comment]
@lploumen Have you by any chance downloaded the zip file instead of cloning the repository?

**Comment by lploumen** [comment]
> 
> 
> @lploumen Have you by any chance downloaded the zip file instead of cloning the repository?

Exactly what I did yes. I didn't know there were differences between the zip file and a repo clone.
I'll try again ! Thank you

**Comment by patriksvensson** [comment]
@lploumen Awesome. Closing this issue but feel free to re-open.

**Comment by lploumen** [comment]
I cloned the spectro.console rep, compiled succesfully but I still can't run the example. I still get the exact error message as I previously had.
