### ISSUE TITLE
Allow SelectionPrompt choices to have markup

### ISSUE THREAD

**Issue by Nikey646** [spectresystems/spectre.console#221]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
To be able to use markup in choices for the `SelectionPrompt<T>` class.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by angelobreuer** [comment]
I would also need this (+1).
I am available to grab this issue if this would be a candidate.
