### ISSUE TITLE
Allow custom texts in prompts

### ISSUE THREAD

**Issue by angelobreuer** [spectresystems/spectre.console#229]
**Is your feature request related to a problem? Please describe.**
It would be useful to customize texts for prompts.

**Why is this needed?**
I need custom texts in prompts for localization purposes, but I think it would be beneficial to allow custom texts.

**Describe the solution you'd like**
A solution to customize texts in prompts.

**Additional context**

```cs
var prompt = new MultiSelectionPrompt<string>()
    .ShowMoreOptions(text: "Press [Up] or [Down]-Arrow to show more.")
    ...
```

**Comment by patriksvensson** [comment]
@angelobreuer I absolutely agree 👍🏻
