### ISSUE TITLE
`--version` does not work when published as .NET 5/PublishSingleFile

### ISSUE THREAD

**Issue by MiloszKrajewski** [spectresystems/spectre.console#242]
**Information**
 - OS: Win 10
 - Version: 0.37.1-preview.0.12
 - Terminal: Any

**Describe the bug**

After publishing single file with .NET 5 (`dotnet publish`) `--version` stops working (shows `?`).
![image](https://user-images.githubusercontent.com/4333436/105212435-5ad96600-5b45-11eb-8c48-934e2f30bc53.png)

**To Reproduce**

Create console app with:

```
<PropertyGroup>
  <OutputType>Exe</OutputType>
  <TargetFramework>net5.0</TargetFramework>
  <PublishSingleFile>true</PublishSingleFile>
  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  <Version>1.1.1.1</Version>
</PropertyGroup>
```

create dummy app:

```
class Program
{
	static void Main(string[] args)
	{
		var app = new CommandApp();
		app.Configure(config => config.AddCommand<RunCommand>("run"));
		app.Run(args);
	}
}

public class RunCommand: Command
{
	public override int Execute(CommandContext context) => 0;
}
```

build & publish it:

```
dotnet build
dotnet publish
```

run both:

```
.\bin\Debug\net5.0\win-x64\app.exe --version
.\bin\Debug\net5.0\win-x64\publish\app.exe --version
```

Observe one produces `1.1.1.1` (expected) while the other produces `?`

**Expected behavior**
Both produce version (`1.1.1.1`)

**Screenshots**
Included above.

**Additional context**
So, my guess is it returns `null` from `GetEntryAssembly()` because of some publish single file related shenanigans.

Seems like `Process.GetCurrentProcess().MainModule?.FileVersionInfo.ProductVersion` works for 3.1 and 5.0 but not for 2.2. For 2.2 it returns... version of `dotnet.exe`. LOL.

**Suggestion 1**
Multi-targetting with conditional compilation (GetEntryAssembly() vs `Process.GetCurrentProcess().MainModule`)

**Suggestion 2**
Allow to override version (like `SetApplicationName`)

```
app.Configure(config => {
	config.SetApplicationName("App");
	config.SetApplicationVersion("1.2.3.4-overriden");
	config.AddCommand<RunCommand>("run");
});
```

**Suggestion 3**
Both ;-)

(I guess no 2 is trivial)

**Comment by XGERT420X** [comment]
Thank you

**Comment by patriksvensson** [comment]
@MiloszKrajewski Great catch! Suggestion 3 sounds like a good approach!

Would you want to take a stab at this? Otherwise, I might be able to get around to it tomorrow evening or so (CET timezone).

**Comment by MiloszKrajewski** [comment]
I can take a look, don't worry (I will let you know if I give up).

**Comment by MiloszKrajewski** [comment]
Update:

1. So the warning was always there when I was building single file exe: 
```
warning IL3000: 'System.Reflection.Assembly.Location' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'.
```

2. `System.Reflection.Assembly.Location` returns empty string

Code below was never falling back to `assembly?.GetName()?.Version?.ToString()` it was always short-circuiting to exception handler straight away.
```
try
{
    var info = FileVersionInfo.GetVersionInfo(assembly.Location);
    return info.ProductVersion ?? assembly?.GetName()?.Version?.ToString() ?? "?";
}
catch
{
    return "?";
}
```

3. `<Version>` from csproj translates to `AssemblyInformationalVersionAttribute`
So consistent way to get full assembly version is `assembly?.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion`

4. I'm attaching project showing possible ways to get version to show that I did my homework ;-)

Run `test.cmd`

[GetAssemblyVersion.zip](https://github.com/spectresystems/spectre.console/files/5859397/GetAssemblyVersion.zip)

5. PR comes in a minute
