### ISSUE TITLE
Formatting for tag value in breakdown chart

### ISSUE THREAD

**Issue by phil-scott-78** [spectresystems/spectre.console#252]
**Is your feature request related to a problem? Please describe.**
Be nice if the tag's value could have a custom format. My simple example I'd like to just do a `{0:N}` format on them to get commas, but i could see someone wanting to use something like `4MB`, `49 seconds`, etc

**Describe the solution you'd like**

Maybe something like this?

```csharp
var chart = new BreakdownChart()
    .TagValueFormat(value => $"{value:N}")
    .AddItems(insertReport,
        pair => new BreakdownChartItem(pair.Key, pair.Value, counter++)
    );
```

**Additional context**
I could knock this out in a PR pretty easily if needed.  Nothing pressing, just thought it'd be neat to have.

**Comment by patriksvensson** [comment]
@phil-scott-78 Seen the recently pushed PR? Will this solve it for you?

**Comment by phil-scott-78** [comment]
Yup, takes care of my needs. Reason I was suggesting a `Func` though was a situation where someone might want to display something like file sizes so they'd need more than `Format` provides. Maybe an overload in the future when that time comes

**Comment by patriksvensson** [comment]
@phil-scott-78 I've added the lambda support in the latest preview version (should be on NuGet in 10 minutes or so)

**Comment by phil-scott-78** [comment]
looks good!
![image](https://user-images.githubusercontent.com/2447331/107859891-7fee8b00-6e0a-11eb-8e0c-9008bdb3edf3.png)
