### ISSUE TITLE
Allow setting progress value directly

### ISSUE THREAD

**Issue by Mrxx99** [spectresystems/spectre.console#272]
Currently the ProgressTask only allows changing the value by calling increment but this often is counter intuitive because I want to set the value of the progress. 

Could there be just another method on ProgressTask like `SetValue(double value)` or UpdateValue.

Current alternative is to use it like this `task.Increment(progress - task.Value);` but that is clunky and not intuitive.

**Comment by patriksvensson** [comment]
@Mrxx99 I completely agree! Havign a `SetValue(double value)` method makes a lot of sense. Would you be in a position to submit a pull request for this?

**Comment by OskarKlintrot** [comment]
May I suggest using the same solution as for `MaxValue` to keep things consistent? I can't see any other Set-methods in the class.

So using this solution:

```csharp
/// <summary>
/// Gets or sets the max value of the task.
/// </summary>
public double MaxValue
{
    get => _maxValue;
    set => Update(maxValue: value);
}
```

we get:

```csharp
/// <summary>
/// Gets or sets the value of the task.
/// </summary>
public double Value
{
    get => _value;
    set => Update(value: value);
}
```

Might I open a PR with this change?

**Comment by patriksvensson** [comment]
@OskarKlintrot Yes, I think your approach is better! 👍🏻
