### ISSUE TITLE
Previously set colors is used after the current text is written

### ISSUE THREAD

**Issue by AdmiringWorm** [spectresystems/spectre.console#28]
When the background (also assuming the foreground, but can't be verified) gets changed multiple times (by setting `AnsiConsole.Background`), then after the text has been printed, the previous background color is being used for the rest of the line.

Examples from different shells:

<details>
<summary>PowerShell</summary>

![image](https://user-images.githubusercontent.com/1474648/89626423-b23a9100-d899-11ea-8e3b-e0c1e4aebfb7.png)

</details>

<details>
<summary>CMD</summary>

![image](https://user-images.githubusercontent.com/1474648/89626480-d007f600-d899-11ea-842c-ceeb09a9c315.png)

</details>

<details>
<summary>Windows Terminal</summary>

![image](https://user-images.githubusercontent.com/1474648/89626556-e44bf300-d899-11ea-8b50-ad7fb5b7030a.png)

</details>

<details>
<summary>GNOME Terminal</summary>

![image](https://user-images.githubusercontent.com/1474648/89626639-fa59b380-d899-11ea-9b17-03a432554c41.png)

</details>

<details>
<summary>Konsole Terminal</summary>

![image](https://user-images.githubusercontent.com/1474648/89637275-385ed380-d8aa-11ea-939d-519916fc4097.png)

</details>

I tried to look into why this happens, but I was unable to find the reason.

**Comment by patriksvensson** [comment]
@AdmiringWorm Funny, I just fixed this 😁 Will be fixed once I push #27!

**Comment by patriksvensson** [comment]
@AdmiringWorm Actually, just found a edge case that wasn't covered. Will fix in new PR.

**Comment by AdmiringWorm** [comment]
Hehe, that is what I get for forgetting to push the submit button for several hours.
Glad you managed to identify and fix the issue 😄 

Just pulled in the latest changes, and I can confirm everything works as expected now. 👍 

Now I only need to find out why my font doesn't display the package Unicode characters, and the rounded corners.
But that is a problem on my end.

**Comment by patriksvensson** [comment]
@AdmiringWorm I think I know the answer to that as well.

Are you running it inside cmd.exe by any chance? Rounded corners require true type fonts which isn't supported there, but I have a fix in the pipeline to fall back to a compatible table border if that is detected.

**Comment by AdmiringWorm** [comment]
I actually have it happening in `cmd` (Cascadia Code font), `powershell` (Consolas Font), and in `Windows Terminal` (using Fira Code Font).

**Comment by patriksvensson** [comment]
@AdmiringWorm If you dump the encoding being used, what does it say?

```
Console.OutputEncoding.EncodingName
```

**Comment by AdmiringWorm** [comment]
They all use `Codepage - 850`, I keep trying to force Windows to use `UTF-8`, but it keeps changing back. So I have been giving up on that for the past few weeks.

**Comment by patriksvensson** [comment]
@AdmiringWorm Does it work if you set the encoding manually at the beginning of the program?

```
Console.OutputEncoding = Encoding.Utf8;
```

**Comment by AdmiringWorm** [comment]
@patriksvensson That works for Windows Terminal, but not for Windows PowerShell and CMD.
Also tested in PowerShell Core, but setting the encoding to UTF8 didn't work there as well.

I also tried the following encoding:
- Unicode
- BigEndianUnicode (throws an error during runtime)
- UTF32 (also throws an error during runtime)

I tried a few others as well using their code page number, but neither of these worked, or they didn't support most of the characters.

**Comment by patriksvensson** [comment]
@AdmiringWorm I'll see it I can reproduce it tonight. Cmd.exe doesn't support true type fonts but I'm a bit confused about Windows Terminal and Powershell terminal.

**Comment by patriksvensson** [comment]
@AdmiringWorm I can recreate it in cmd.exe and powershell.exe (if I run with the `-noprofile` flag). I can also recreate it when running cmd.exe and powershell (again without profile) in Windows Terminal.

I got it to work by adding `Console.OutputEncoding = Encoding.UTF8;` at the top of the program (before any call to the AnsiConsole has been done). Need to read up on what implications that might have for other people, but perhaps this should be done by default if running in a legacy console?

**Comment by patriksvensson** [comment]
@AdmiringWorm I've added a fallback for borders on systems that is either legacy or doesn't support Unicode. You can opt-out from this behavior by setting either `Table.SafeBorder` or `Panel.SafeBorder` to `false`.
