### ISSUE TITLE
Add ExtendedProperties dictionary to ProgressTask for custom columns

### ISSUE THREAD

**Issue by Yaroshvitaliy** [spectresystems/spectre.console#280]
It would be great to have a property (e.g. Dictionary<string, object> inProgressTask to be used for custom columns.
The reason is that `Description` property has some restrictions (cannot be emty, is trimmed, one line, etc) that's why it cannot be used for passing all needed information.
In my particular case for my MultilineColumn I had to find workarounds to solve the problem.

**Comment by phil-scott-78** [comment]
Take a look at `task.State`. It has a couple of method `Get` and `Update`. The one restriction is that the data being stored as state must be in a struct. Code looks something along the lines of this (excuse any errors, typed it out on my phone)

```csharp
struct CustomData 
{
    public const string Key = "CustomData";

    public string CustomString {get; set;}
    public int CustomInt {get; set;}
}

// in your progress loop
progressTask.State.Update<CustomData>(CustomData.Key
                            _ => new CustomData() { CustomString = "example", CustomInt = 123 });

// in your custom progress bar
var data= task.State.Get<CustomData>(CustomData.Key);
```

**Comment by Yaroshvitaliy** [comment]
Got it, thank you wery much, but I haven't found this functionality in documentation...

**Comment by phil-scott-78** [comment]
Yup. Docs will definitely need more work before we can make this a 1.0 release. 

Glad state works out. If you need a further example, I had good luck using it with my custom column here - https://github.com/phil-scott-78/dotnet-soddi/blob/master/src/Soddi/ProgressBar/TorrentProgressBarColumn.cs
