### ISSUE TITLE
Make ProgressTask implement IProgress<double> for smoother interopability

### ISSUE THREAD

**Issue by Tyrrrz** [spectresystems/spectre.console#285]
Hello 🙂 
Was looking through the code because I was interested in using the Progress widget in one of my applications.
Let me know if this feature suggestion makes sense.

**Is your feature request related to a problem? Please describe.**

.NET has a standard way of reporting progress, which is through the [`IProgress<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.iprogress-1) and [`Progress<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.progress-1). Currently, [`ProgressTask`](https://github.com/spectresystems/spectre.console/blob/fa731070d8489be3b10bb33c01b9c41b3b62076e/src/Spectre.Console/Widgets/Progress/ProgressTask.cs#L10) does not implement `IProgress<double>`. If it did, it would be possible to pass `ProgressTask` directly to methods that expect an instance of `IProgress<double>`.

**Describe the solution you'd like**

The solution would be to implement `IProgress<double>` on `ProgressTask` and delegate the `Report(...)` method directly to `Update(...)` method. If necessary, the interface could be implemented explicitly so that `Report(...)` method is not visible on `ProgressTask` to the consumers, to avoid confusion with `Update(...)`.

Note that, unlike how `Increment(...)` works, `IProgress<T>.Report(...)` takes the _final_ progress value after increment.

**Describe alternatives you've considered**

The alternative is to wire up `Progress<double>` manually in user code, which is completely fine too. However, since it's a standard .NET abstraction, I think it makes sense to add this capability to Spectre.Console directly.

**Additional context**

https://devblogs.microsoft.com/dotnet/async-in-4-5-enabling-progress-and-cancellation-in-async-apis/

**Comment by phil-scott-78** [comment]
I think that's a clever idea. I would propose that we implement it explicitly so in `ProgressTask.cs` we'd see something like

```csharp
public sealed class ProgressTask : IProgress<double>
{
        /// <inheritdoc />
        void IProgress<double>.Report(double value)
        {
            Update(increment: value - Value);
        }

        // ....
}
```

By making it explicit people not using this functionality wouldn't confusingly see the `Report` method along with `Increment` in their intellisense when working with a `ProgressTask`, but they'd still get everything to play nice with the standard reporting APIs. 

And as you said, even with adding this functionality they can still roll their own (e.g. I'm using `IProgress<(tuple)>` heavily) and not worry about this getting in their way.
