### ISSUE TITLE
Examples of hidden commands are shown in the help text

### ISSUE THREAD

**Issue by bddckr** [spectresystems/spectre.console#290]
**Information**
 - OS: All three: Windows, Linux, MacOS
 - Version: 0.37.1-preview.0.36
 - Terminal: Windows Terminal

**Describe the bug**
If you add an example for a command that is hidden, the example shows in the root command's help text.

**To Reproduce**

```c#
config
    .AddCommand<MyCommand>("test")
    .WithDescription("This is a test command")
    .WithExample([| "test", "--some-arg", "123" |])
    .IsHidden();
```

**Expected behavior**
Examples of hidden commands should only show up in the help text when explicitly asking for *that* command's help text. For commands that are a root of that command it should not show the example, including the default command.

**Additional context**
Note: The command is actually hidden correctly, it's just the example that shows up in the help text.

**Comment by bddckr** [comment]
Having a look at whether I can raise a PR for this:

I think this method needs some filtering based on the command's `IsHidden` property.
https://github.com/spectresystems/spectre.console/blob/da9c6ee4c2d2d0c5374e51231073346144746dea/src/Spectre.Console/Cli/Internal/HelpWriter.cs#L166-L202

I'm not yet sure how the nesting of commands works, though. I think it's important that we keep the ability to show the example(s) for the command, if the user specifically asks for that command's help text...

**Comment by patriksvensson** [comment]
@bddckr I'll take a look at this tonight and will see if I can give some insight into this!

**Comment by phil-scott-78** [comment]
@bddckr, I think you were spot on with the `HelpWriter.cs`. Looks like on line 187 if we filter out `IsHidden` everything falls into place.

The first conditional is checking to see if we have a specific command with example (`command?.Examples`) and if not are there any examples for the root of the configuration (`model.Examples`). So if we have either of those situations the specifics will be displayed regardless of `IsHidden` is set.

If you want to submit a PR and verify with the `Cli/Demo` project which has a few nested commands with help I think we should be set for a PR.
