### ISSUE TITLE
SelectionPrompt: Support PgUp, PgDown, Home, and End keys

### ISSUE THREAD

**Issue by patriksvensson** [spectresystems/spectre.console#296]
**Is your feature request related to a problem? Please describe.**
Would be great if we supported `PgUp`, `PgDown`, `Home`, and `End` keys for `SelectionPrompt`

**Additional context**
I can take a stab at this tonight

**Comment by chucker** [comment]
Shouldn't this work as of 0.46.0? Scrolling with Up/Down works, but paging with PgUp/PgDown doesn't seem to.
