### ISSUE TITLE
"Hello" in French is misspelled

### ISSUE THREAD

**Issue by ycrumeyrolle** [spectresystems/spectre.console#50]
Hi,
https://github.com/spectresystems/spectre.console/blob/8a01b93acad83118d090f4da8a8d9e66ed0f476e/examples/Table/Program.cs#L62

"Bounjour" should be replaced by "Bonjour"

**Comment by patriksvensson** [comment]
@ycrumeyrolle Ouch, that is embarrassing. Will fix that asap 😅
