### ISSUE TITLE
Support ANSI Hyperlinks in output

### ISSUE THREAD

**Issue by AdmiringWorm** [spectresystems/spectre.console#75]
It would be handy if there were support in spectre.console to output ANSI hyperlinks (clickable links) in the terminals that support this feature.

While there are currently only a handful of terminals that currently support this.
Current state of support (per 2020-05-31) can be seen here: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

From my own testing, I have found that GNOME Terminal supports these links, and partially Windows Terminal (mainly only that it won't choke when ANSI hyperlinks are used).

**Comment by patriksvensson** [comment]
@AdmiringWorm Absolutely. Need to do a little research on my own and think about how this could be implemented, but a great idea!

**Comment by patriksvensson** [comment]
@AdmiringWorm I've done some thinking and going to add support for this tonight.

**Comment by patriksvensson** [comment]
@AdmiringWorm This has been merged and will be available in 0.21.0. If you want to play with this feature now, you can always use the preview package 😊

**Comment by AdmiringWorm** [comment]
Will do, thank you for adding the support :smile_cat:
