### ISSUE TITLE
Cell Width issues when rendering emojis in table cells

### ISSUE THREAD

**Issue by CarlosLanderas** [spectresystems/spectre.console#78]
Hello, first of all, thanks for this amazing project. It enable us to build cool dotnet tools :)

I'm trying to render a table that contains emojis, and depending on the emoji (I suppose because of their length), the table renders ok with some emojis and it has an extra spacing with others.

Here is some sample code:

```csharp
            var hcTable = new Table().SetBorder(Border.Rounded);
            hcTable.AddColumn(new TableColumn("Name ") { Padding = new Padding(10, 10), Alignment = Justify.Center });
            hcTable.AddColumn(new TableColumn(new Markup($"Status ✔️")) { Padding = new Padding(10, 10), Alignment = Justify.Center });
            hcTable.AddColumn(new TableColumn("Description ℹ") { Padding = new Padding(10, 10), Alignment = Justify.Center });
            hcTable.AddColumn(new TableColumn("Duration 🕐 ") { Padding = new Padding(10, 10), Alignment = Justify.Center });
            hcTable.AddRow(new Text("name"), new Markup($"💚 some text"), new Text("some text"), new Text("Some text"));
            hcTable.AddRow(new Text("name"), new Markup($"❌ some text"), new Text("some text"), new Text("Some text"));
            hcTable.AddRow(new Text("name"), new Markup($"💚 some text"), new Text("some text"), new Text("Some text"));
            AnsiConsole.Render(hcTable);
```

![image](https://user-images.githubusercontent.com/16475649/93174455-48ca5f80-f72e-11ea-88a1-af82f1de79fb.png)

As you can see it does not happen with the 💚   but happens with the ❌ and also in table headers. They report lengths of 2 and 1 (4 and 3 bytes).

I see you are considering this extra spacing in the unit tests, but is there any chance to correctly calculate cell length and width when having emojis?

https://github.com/spectresystems/spectre.console/blob/main/src/Spectre.Console.Tests/Unit/PanelTests.cs#L158

Thanks

**Comment by patriksvensson** [comment]
@CarlosLanderas I have a method to calculate the cell length of a unicode rune, which is working, but I suspect I've forgot to use it somewhere in the code base. I'll investigate

**Comment by patriksvensson** [comment]
@CarlosLanderas Yeah, it's a bug in the unicode codepoint width calculator. Will see if I can find it tonight and push a fix.

**Comment by CarlosLanderas** [comment]
Thanks @patriksvensson  :)

**Comment by patriksvensson** [comment]
It should be better now with the release of 0.20.0.
Closing this for now since it's not going to get better until there's a better way of calculating emoji widths.
